'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CS_BTE_Launcher.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2_anniversary_of_the_painting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2_anniversary_of_the_painting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property All_about_lovin__you_paint() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("All_about_lovin_'you_paint", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Army_rank_spray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Army_rank_spray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bandspray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bandspray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property basic_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("basic_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property basic_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("basic_s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Battalion_rank_spray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Battalion_rank_spray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg_pic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_pic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Brigade_rank_spray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Brigade_rank_spray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_bulletin_c() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_bulletin@c", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_bulletin_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_bulletin@n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_bulletin_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_bulletin@o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_cancel_c() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_cancel@c", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_cancel_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_cancel@n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_cancel_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_cancel@o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_channel_c() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_channel@c", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_channel_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_channel@n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_channel_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_channel@o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_exit_c() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_exit@c", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_exit_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_exit@n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_exit_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_exit@o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_myinfo_c() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_myinfo@c", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_myinfo_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_myinfo@n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_myinfo_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_myinfo@o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_option_c() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_option@c", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_option_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_option@n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_option_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_option@o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_quest_c() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_quest@c", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_quest_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_quest@n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_quest_new_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_quest_new@n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_quest_new_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_quest_new@o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_quest_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_quest@o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_server_c() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_server@c", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_server_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_server@n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_server_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_server@o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_store_c() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_store@c", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_store_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_store@n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_store_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_store@o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_weaponmaking_c() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_weaponmaking@c", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_weaponmaking_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_weaponmaking@n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btn_weaponmaking_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_weaponmaking@o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cannotuse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cannotuse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Choijiyoon_spray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Choijiyoon_spray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property coinbox2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coinbox2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Corps_rank_spray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Corps_rank_spray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Crissspray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Crissspray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property csbte_bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("csbte_bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property csbte_bg_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("csbte_bg_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cso() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cso", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cswd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cswd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ctspray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ctspray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dm_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dm_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dm_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dm_s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dr_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dr_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dr_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dr_s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EricaSpray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EricaSpray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fun_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fun_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fun_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fun_s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gdm_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gdm_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gdm_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gdm_s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gongmospray01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gongmospray01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gongmospray02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gongmospray02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gongmospray03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gongmospray03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gongmospray07() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gongmospray07", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gongmospray08() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gongmospray08", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gongmospray09() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gongmospray09", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gongmospray10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gongmospray10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hd_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hd_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hd_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hd_s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Host_regular_zombie_spray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Host_regular_zombie_spray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Jenniferspray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jenniferspray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ladderspray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ladderspray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Love_the_debris_painting__left_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Love_the_debris_painting_(left)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Love_the_debris_painting__right_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Love_the_debris_painting_(right)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property luckyitem_c() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("luckyitem@c", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property luckyitem_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("luckyitem@n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property luckyitem_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("luckyitem@o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MeiSpray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MeiSpray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property myinfo_c() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("myinfo@c", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property myinfo_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("myinfo@n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property myinfo_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("myinfo@o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Natashaspray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Natashaspray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Newyearspray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Newyearspray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nndm_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nndm_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nndm_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nndm_s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property No_photo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("No_photo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property none_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("none_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property none_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("none_s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noticetitle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noticetitle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property npc_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("npc_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property npc_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("npc_s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pczombi_spray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pczombi_spray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Platoon_rank_spray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Platoon_rank_spray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property random_cso() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("random_cso", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property randombox_c() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("randombox@c", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property randombox_d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("randombox@d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property randombox_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("randombox@n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property randombox_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("randombox@o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ritsuka_spray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ritsuka_spray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Skull_rabbit_painting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skull_rabbit_painting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Skullspray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skullspray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sl8gold_spray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sl8gold_spray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sniper_king_painting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sniper_king_painting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property taskbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("taskbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property td_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("td_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property td_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("td_s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property textbox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("textbox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Trspray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Trspray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tt1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tt1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tt2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tt2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Valentines_section_painting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Valentines_section_painting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Watergun_spray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Watergun_spray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Wc13spray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wc13spray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Wcg12spray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wcg12spray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Xmas_spray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Xmas_spray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Xmasspray09() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Xmasspray09", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Yurispray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Yurispray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zb1_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zb1_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zb1_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zb1_s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zb3_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zb3_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zb3_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zb3_s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zb4_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zb4_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zb4_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zb4_s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ze_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ze_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ze_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ze_s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
